### ISSUE TITLE
HTTP Basic auth when trying to push from github to gitlab?

### ISSUE THREAD

**Issue by PenzinAlexander** [wei/git-sync#15]
Hi there. 
I'm using gitlab, which is protected by HTTP Basic auth. 
Is there any way to set up credentials for that? 

Thank you

**Comment by wei** [comment]
Yes you can use HTTPS clone url with access token in it.

**Comment by PenzinAlexander** [comment]
> Yes you can use HTTPS clone url with access token in it.

I'm already using https clone url with access token. But my site is hided from others with nginx basic auth. 
Could you please share example? Thank you

**Comment by wei** [comment]
How do you checkout / clone locally?

**Comment by PenzinAlexander** [comment]
I tried to copy from my github to cloud-gitlab. 
That worked for me. 

```
 source_repo: "https://gitlab.com/PenzinAlexander/my-test-project"
        source_branch: "master"
        destination_repo: "https://root:_tokenhere_@gitlab.com/root/filetest.git"
        destination_branch: "master"
```

But then, i've created my own instance of gitlab at my own server. 
It's protected with HTTP Basic auth.  I mean if someone opens my server's URL in browser will no be able to access My Gitlab without Basic auth login and pass. 

It's possible to send basic auth credentials this way: https:// basicauth_login : basicauth_pass @ host.com

But to push to gitlab repository, i need to send GitLab's auth credentials too. How can i do this? 

Thank you so much

**Comment by wei** [comment]
Yeah it looks like you have a nested basic auth situation. How do you checkout / clone locally?

**Comment by PenzinAlexander** [comment]
I do not clone locally. I just setting up this for the first time

**Comment by PenzinAlexander** [comment]
https://gitlab.example.com/api/v4/projects?private_token=<your_access_token>

Will this work?

**Comment by wei** [comment]
I don't know how nested basic auth would work. You can do some research on how to do it locally if you would like this behavior. 

As an alternative, I recommend using SSH Clone Url with the deploy key if you have it enabled in your GitLab instance..

If SSH isn't feasible, another idea is try using `http.extraHeader` to authenticate using a different header instead of Basic Authentication. You can try this locally before trying it on Actions.

I'm unable to provide further help until you're able to get it working locally because GitHub can do anything you can do locally, vise-versa, GitHub cannot do what you can't do locally.
